// <auto-generated />
using System;
using Banane.DataObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Banane.Migrations
{
    [DbContext(typeof(BananeDb))]
    [Migration("20260618173526_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Banane.ObjetMetier.ABSENCE", b =>
                {
                    b.Property<int>("IdAbsence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAbsence"));

                    b.Property<DateTime>("DateAbsence")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEtudiant_fk_Absence")
                        .HasColumnType("integer");

                    b.Property<int>("IdMatiere_fk_Absence")
                        .HasColumnType("integer");

                    b.HasKey("IdAbsence");

                    b.ToTable("ABSENCE");
                });

            modelBuilder.Entity("Banane.ObjetMetier.CONVERSATION", b =>
                {
                    b.Property<int>("IdConversation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConversation"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.Property<string>("TypeConversation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdConversation");

                    b.ToTable("CONVERSATION");
                });

            modelBuilder.Entity("Banane.ObjetMetier.DOCUMENT", b =>
                {
                    b.Property<int>("IdDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDocument"));

                    b.Property<int>("IdMatiere_fk_Document")
                        .HasColumnType("integer");

                    b.Property<string>("TypeDocument")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlDocument")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdDocument");

                    b.HasIndex("IdMatiere_fk_Document");

                    b.ToTable("DOCUMENT");
                });

            modelBuilder.Entity("Banane.ObjetMetier.FILIERE", b =>
                {
                    b.Property<int>("IdFiliere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFiliere"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.HasKey("IdFiliere");

                    b.ToTable("FILIERE");
                });

            modelBuilder.Entity("Banane.ObjetMetier.MATIERE", b =>
                {
                    b.Property<int>("IdMatiere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMatiere"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IdEnseignant_fk")
                        .HasColumnType("integer");

                    b.Property<int?>("IdNiveauScolaire_fk_Matiere")
                        .HasColumnType("integer");

                    b.Property<string>("Jour")
                        .HasColumnType("text");

                    b.Property<int?>("Time")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdMatiere");

                    b.HasIndex("IdEnseignant_fk");

                    b.HasIndex("IdNiveauScolaire_fk_Matiere");

                    b.ToTable("MATIERE");
                });

            modelBuilder.Entity("Banane.ObjetMetier.MEMBRECONVERSATION", b =>
                {
                    b.Property<int>("IdMembreGroupe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMembreGroupe"));

                    b.Property<int>("IdConversation_fk_MembreC")
                        .HasColumnType("integer");

                    b.Property<int>("IdMembre_fk_MembreC")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("createur")
                        .HasColumnType("boolean");

                    b.HasKey("IdMembreGroupe");

                    b.HasIndex("IdConversation_fk_MembreC");

                    b.HasIndex("IdMembre_fk_MembreC");

                    b.ToTable("MEMBRECONVERSATION");
                });

            modelBuilder.Entity("Banane.ObjetMetier.MESSAGE", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMessage"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdConversation_fk_Message")
                        .HasColumnType("integer");

                    b.Property<int>("IdExpediteur_fk")
                        .HasColumnType("integer");

                    b.HasKey("IdMessage");

                    b.HasIndex("IdConversation_fk_Message");

                    b.HasIndex("IdExpediteur_fk");

                    b.ToTable("MESSAGE");
                });

            modelBuilder.Entity("Banane.ObjetMetier.NIVEAUSCOLAIRE", b =>
                {
                    b.Property<int>("IdNiveauScolaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNiveauScolaire"));

                    b.Property<int>("IdFiliere_fk_NiveauScol")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdNiveauScolaire");

                    b.HasIndex("IdFiliere_fk_NiveauScol");

                    b.ToTable("NIVEAUSCOLAIRE");
                });

            modelBuilder.Entity("Banane.ObjetMetier.UTILISATEUR", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<DateOnly?>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroTelephone")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("photoUrl")
                        .HasColumnType("text");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("UTILISATEUR");

                    b.HasDiscriminator().HasValue("UTILISATEUR");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Banane.ObjetMetier.ADMINISTRATEUR", b =>
                {
                    b.HasBaseType("Banane.ObjetMetier.UTILISATEUR");

                    b.HasDiscriminator().HasValue("ADMINISTRATEUR");
                });

            modelBuilder.Entity("Banane.ObjetMetier.ENSEIGNANT", b =>
                {
                    b.HasBaseType("Banane.ObjetMetier.UTILISATEUR");

                    b.Property<string>("Matricule")
                        .HasColumnType("text");

                    b.ToTable("UTILISATEUR", t =>
                        {
                            t.Property("Matricule")
                                .HasColumnName("ENSEIGNANT_Matricule");
                        });

                    b.HasDiscriminator().HasValue("ENSEIGNANT");
                });

            modelBuilder.Entity("Banane.ObjetMetier.ETUDIANT", b =>
                {
                    b.HasBaseType("Banane.ObjetMetier.UTILISATEUR");

                    b.Property<int?>("Filiere")
                        .HasColumnType("integer");

                    b.Property<int?>("IdNiveauScolaire_fk_Etudiant")
                        .HasColumnType("integer");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("IdNiveauScolaire_fk_Etudiant");

                    b.HasDiscriminator().HasValue("ETUDIANT");
                });

            modelBuilder.Entity("Banane.ObjetMetier.DOCUMENT", b =>
                {
                    b.HasOne("Banane.ObjetMetier.MATIERE", "DocumentMatiere")
                        .WithMany()
                        .HasForeignKey("IdMatiere_fk_Document")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentMatiere");
                });

            modelBuilder.Entity("Banane.ObjetMetier.MATIERE", b =>
                {
                    b.HasOne("Banane.ObjetMetier.ENSEIGNANT", "Enseignant")
                        .WithMany("Matiere_Enseigner")
                        .HasForeignKey("IdEnseignant_fk")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Banane.ObjetMetier.NIVEAUSCOLAIRE", "NiveauScolaire")
                        .WithMany("Matieres")
                        .HasForeignKey("IdNiveauScolaire_fk_Matiere")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Enseignant");

                    b.Navigation("NiveauScolaire");
                });

            modelBuilder.Entity("Banane.ObjetMetier.MEMBRECONVERSATION", b =>
                {
                    b.HasOne("Banane.ObjetMetier.CONVERSATION", "Groupe")
                        .WithMany("Membres")
                        .HasForeignKey("IdConversation_fk_MembreC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banane.ObjetMetier.UTILISATEUR", "Membre")
                        .WithMany("Conversations")
                        .HasForeignKey("IdMembre_fk_MembreC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Groupe");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("Banane.ObjetMetier.MESSAGE", b =>
                {
                    b.HasOne("Banane.ObjetMetier.CONVERSATION", "conversation")
                        .WithMany("Messages")
                        .HasForeignKey("IdConversation_fk_Message")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banane.ObjetMetier.UTILISATEUR", "Expediteur")
                        .WithMany()
                        .HasForeignKey("IdExpediteur_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediteur");

                    b.Navigation("conversation");
                });

            modelBuilder.Entity("Banane.ObjetMetier.NIVEAUSCOLAIRE", b =>
                {
                    b.HasOne("Banane.ObjetMetier.FILIERE", "Filiere")
                        .WithMany("NiveauxScolaires")
                        .HasForeignKey("IdFiliere_fk_NiveauScol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filiere");
                });

            modelBuilder.Entity("Banane.ObjetMetier.ETUDIANT", b =>
                {
                    b.HasOne("Banane.ObjetMetier.NIVEAUSCOLAIRE", "NiveauScolaire")
                        .WithMany("Etudiants")
                        .HasForeignKey("IdNiveauScolaire_fk_Etudiant");

                    b.Navigation("NiveauScolaire");
                });

            modelBuilder.Entity("Banane.ObjetMetier.CONVERSATION", b =>
                {
                    b.Navigation("Membres");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Banane.ObjetMetier.FILIERE", b =>
                {
                    b.Navigation("NiveauxScolaires");
                });

            modelBuilder.Entity("Banane.ObjetMetier.NIVEAUSCOLAIRE", b =>
                {
                    b.Navigation("Etudiants");

                    b.Navigation("Matieres");
                });

            modelBuilder.Entity("Banane.ObjetMetier.UTILISATEUR", b =>
                {
                    b.Navigation("Conversations");
                });

            modelBuilder.Entity("Banane.ObjetMetier.ENSEIGNANT", b =>
                {
                    b.Navigation("Matiere_Enseigner");
                });
#pragma warning restore 612, 618
        }
    }
}
